### ISSUE TITLE
Fix overlapping top textviews

### ISSUE THREAD

**Issue by civyshk** [reloZid/android-anuto#100]
Recent merges (speed up & enemy counter) have added text to top bar. The views now overlap, sometimes. It may depend on language settings and screen size.
Here is a shot from a 5.2'' screen:

[![Screenshot_2017-07-10-18-47-42.png](https://s3.postimg.org/sbh604pbn/Screenshot_2017-07-10-18-47-42.png)](https://postimg.org/image/c0h23tctr/)

**Comment by reloZid** [comment]
Thanks for the hint. This is one of the few things I want to get fixed before creating the next release.

**Comment by reloZid** [comment]
BTW: Do you feel comfortable with the size of the faster/slower buttons on your screen?

**Comment by gomesar** [comment]
Maybe "credits", "lives", and "Speed" can be substituted by symbols or icons? 
Or "speed: " can be simply changed to "SPD: "..

**Comment by civyshk** [comment]
> BTW: Do you feel comfortable with the size of the faster/slower buttons on your screen?

Not really. I tried to remove the margin of those tiny buttons but the result was still not pleasant enough. Anyway, there's just too little room there for everything to fit.

Besides shortening the labels (crdts, lvs, spd), what do people think of this option?
[![newbar.png](https://s4.postimg.org/bn7sflfu5/newbar.png)](https://postimg.org/image/7e32dfckp/)
I don't have time to test that right now, maybe @beothorn wants to try? Throw your opinions, please.

**Comment by beothorn** [comment]
For the buttons my first idea was something like
<< 2x >>
but there was no space . I thought about adding a new panel on the bottom, but didn't wanted to mess the original layout.

For shortening the labels, the localization strings would have to be changed too, and for different languages the rules to shorten words are different. A new translation would be needed.

The icons idea is a good alternative. We already have universally recognized icons for lifes :heart: , credits :dollar: and bonus :heavy_plus_sign: . Speed and wave would be a problem.
Using icons would buy some room to enlarge the speed buttons. A step further could be replacing all buttons for icons too.

Other options
 - A new panel on the bottom 
 - Getting rid of next wave button, clicking on screen to call next wave (would need a hint or something to show up on first play)
 - Speed up by swiping, remove buttons and show only speed on header
 - Making labels smaller

I'll give it a try

**Comment by gomesar** [comment]
Good points @beothorn. 
I'll put my suggestion (using previous opinios) on the brainstorm:
![anutotd-header](https://user-images.githubusercontent.com/8822070/28143956-fa2b740e-673e-11e7-8c2b-584c3e139d44.png)

Maybe the "Next" button come suffer to the same space problem, so the icon on top may be the best option.

**Comment by beothorn** [comment]
@gomesar nice icons :)
Another option that maybe it is easier to do is drop the speed buttons < > entirely, make the 1x a button that goes around from 8x back to 1x, keeping it where it is nowor moving it up .
I've already starting experimenting here
https://github.com/beothorn/android-anuto/tree/noSpaceOnHeader
but your icons are much better. Can I ask you to commit them on these branch? thanks

**Comment by gomesar** [comment]
<o>
Thanks @beothorn, I used GIMP to edit @civyshk print, trying to maintain the game style. 
In which specifications the files must be? .PNG, 128x128?

**Comment by beothorn** [comment]
128x128 is cool

**Comment by beothorn** [comment]
![anuto](https://user-images.githubusercontent.com/410600/28146132-e58226c4-674d-11e7-8228-9ecef530bbc1.png)

Saved space using a single button for speed used som temporary icons too

**Comment by beothorn** [comment]
Using heart.png

![anuto](https://user-images.githubusercontent.com/410600/28146646-d1f86c40-6751-11e7-8a26-9ac15358df42.png)

**Comment by reloZid** [comment]
I like the icons. And also the idea of using just one button for the game speed showing the actual value. But maybe the 8x option should be removed, because if you're playing at 2x and you want to go back to default speed you have to step through the 8x option which is extremely fast.

Another option I see is to remove the tower icons from the header and replace them by just a "Build" button. This opens a popup which lets you select the tower you want to build. This way we have more space to add new towers.

I don't want to increase the height of the header or add a footer because the aspect ratio of the map fits perfectly on most displays.

**Comment by civyshk** [comment]
I see two options:

1. The new build tower button will be necessarily the way to go when there are more towers available. This leaves space for the speed double button which in turn allows the 8x speed but will probably delay the upcoming release.

2. Fix the current layout by using the new icons shown above and a [spinner](https://developer.android.com/guide/topics/ui/controls/spinner.html). The spinner doesn't force us to drop the 8x speed and fits in the size of a single button. And the build tower button can still be done without a rush.

**Comment by beothorn** [comment]
Expandindo the idea, another option is show a pop-up with the towers when clicking an empty wall block. No build button needed. 

I was playing and I realized that what I wanted with the speed button was just a fast forward, not controlling the game speed. So, maybe it would be better to make it so the game run at 8x while the button is pressed and normal speed otherwise? Unless there is value on changing and keeping  the game speed. 

I will experiment with the spinner.

**Comment by reloZid** [comment]
As a quick solution I replaced the two speed buttons by a single one which toggles fast forward and normal speed. This makes the speed label obsolete. I leave this issue open for a moment, I still think that using icons and placing tower with a popup would be a nicer solution.

**Comment by ManaUser** [comment]
The speed control is a welcome addition, but on my small screen it's still overlapping the 4th turret type. (To be clear this is the new 1x/4x toggle version).

**Comment by reloZid** [comment]
What is your screen size and resolution?

**Comment by ManaUser** [comment]
Let me just post a screenshot, that should answer your question, I hope. DPI is set for 260, if that's helpful in any way.
![anutoscreenshot](https://user-images.githubusercontent.com/5668085/28906727-4e31be74-77ce-11e7-8ba3-cdbdcffd8eae.png)

**Comment by civyshk** [comment]
So a ~4.2" screen (normal size) and 260dpi (hdpi).

**Comment by reloZid** [comment]
Fixed with separate popup for the selecting tower.
