### ISSUE TITLE
map "Waiting line" wrong starting point

### ISSUE THREAD

**Issue by aligator** [reloZid/android-anuto#106]
Look at the screenshot

![screenshot_20170731-215107](https://user-images.githubusercontent.com/663900/28795635-e39d9f54-763a-11e7-833a-e9570dd97067.png)

**Comment by edent** [comment]
Also on Civyshk.  I think it's quite a cool effect - but I don't know if it is intentional :-)

Nexus 6  running 7.1.2
![screenshot_20170801-134410](https://user-images.githubusercontent.com/837136/28825843-b9e4f25e-76bf-11e7-8ffc-6ac7f84c9bb7.png)

**Comment by civyshk** [comment]
This is fixed in v0.3-2, so upgrade to it when you can. Thanks for reporting anyway.
