### ISSUE TITLE
What am I supposed to do?

### ISSUE THREAD

**Issue by t-rocks** [reloZid/android-anuto#109]
I download the game, opened it, and my only option is to press next wave.  Next wave of what?  What's happening?  I press next wave, a bunch of boxes March through the maze.  I cant interact with the boxes or the map in any way.  I press next wave again.  Same thing.  I press it again and this tine there's a another wave of... blobs, I don't know, that follow the third wave if boxes.  Then I get a game over screen and a score.  What the hell is the score for?  Then I come here and people are talking about various elements of the game and I have zero idea how this is even a game.

**Comment by gomesar** [comment]
Hi t-rocks,
I believe you never had play a Tower Defense game before, and it's great that you come ask us ;]
In short: You can slide towers into some map places, and do another things with they.
(I think the discover is one of most exciting parts of games, so I'm trying to tell you just the core)

And the big plot behind it is something like that:
![example](https://user-images.githubusercontent.com/8822070/29389913-66c5e79e-82c3-11e7-8eb9-3c2ce1e91d65.jpg)
(A draft of Elemental TD, developed in Warcraft III -FT map editor.)

I hope you enjoy the game, and probably someone with a better english will come to answer you.

Tip: In general, quality is better than quantity.

**Comment by t-rocks** [comment]
Thanks gomesar
