### ISSUE TITLE
Free unlimited credit bug

### ISSUE THREAD

**Issue by AlexisCaffa** [reloZid/android-anuto#11]
Lower selling price of the **all** upgraded items.

Example: 
If I put the last gun and upgrade it: 
500 + 800 = 1300
then I can sell it at 1750 !!

Free unlimited credit !!

**Comment by reloZid** [comment]
I am pretty sure this was fixed with #7 (released with v0.1-5). On which app version did this happen?

**Comment by AlexisCaffa** [comment]
v0.1-4
