### ISSUE TITLE
Hiding tower options under Build button

### ISSUE THREAD

**Issue by gloryroad1** [reloZid/android-anuto#117]
Am I alone in finding the relatively recent consoliation of the tower options under a Build button extremely awkward ?  Can they be put back the way they were or can their consoliation be made a setting option ?

**Comment by reloZid** [comment]
Actually there was a big discussion about this button (see issues #100 and #112). With the newest release (v0.3-5) the button is shown only if there is not enough space. If you think that is not the case for you please show a screenshot.

**Comment by gloryroad1** [comment]
Sorry to have been a bother.  Early on I had seen some of the discussion about the tower menu but not mention of the rollback in a new version 0.3-5.  F-Droid has assured me v.0.3-4 was the latest for my Samsung Tab S, 8.4-inch tablet, even today, but finally offered 0.3-5 a few minutes ago after I persisted and the tower button menu now is gone.
