### ISSUE TITLE
strategy development

### ISSUE THREAD

**Issue by treakiandroid** [reloZid/android-anuto#119]
Hi,

We know that this isnt an classic issue, but i couldn't find an open discussion board about this project...
After looking to that board and found out how far others came and how only far we came (0nly 205.787 points in the original level and the highest 334.892 in the level with the 5 lines for example on this device) we planed to build up a better strategy based of some statistics. First of all we have to gather all data of the different towers like this:

![screenshot_2018-03-01-02-46-52-034](https://user-images.githubusercontent.com/7935237/36823287-b2c220c6-1cfc-11e8-95e0-3c05d04fb4af.jpeg)

After that we have to build some statistics based abstract from that data and build some new advanced strategy based on that. But before putting any more effort in this we would like to ask if others have done already things in this direction and are willing to share them. Thanks a lot in advance.

**Comment by reloZid** [comment]
I've added the sheet which I used to do the recent balancing update to the repository: https://github.com/reloZid/android-anuto/raw/master/sheets/tower_balancing.xlsx

**Comment by reloZid** [comment]
Moving to #142.
