### ISSUE TITLE
What are the significance of the yellow circles?

### ISSUE THREAD

**Issue by govvin** [reloZid/android-anuto#125]
What are the significance of the yellow circles? I don't notice them at lower levels.

![image](https://user-images.githubusercontent.com/5821688/42415696-81d85a46-8289-11e8-82dc-d266174420ec.png)

**Comment by betsythefc** [comment]
The yellow circles are the area of effect for the missiles.

**Comment by govvin** [comment]
@betsythefc how come they're visible in earlier levels even if I already have missile towers?

**Comment by Acters** [comment]
any explosive will create it; like before you upgrade to the missile tower. the tower that costs 250. It's like asking why the lasers are red and a line on the screen. the yellow ringed circles that are not filled in when you tap on a tower is the area of range for that tower.
