### ISSUE TITLE
level 71 consistantly overpowered

### ISSUE THREAD

**Issue by itsbentheboy** [reloZid/android-anuto#139]
Maybe i'm just a bad designer, but it seems that every course i've made is defeated on level 71. 

On this level, the only thing that spawns are the Star healers, and no matter the DPS of my system, there is nowhere near enough dps on any track length to defend against all those healers at once. I basically plan my entire game around it at this point, and still end up losing. 

It's unfortunate because i want to get into more end-game stuff. 

I'd be happy to help out with some contributions, but i'd need some help knowing where to look in the code. I'm not a skilled programmer, but I do know enough that i might be able to take a look at adding some code. Is there something that decides what kind of enemies are spawned at each level, or is it maybe a list somewhere that picks types.

**Comment by reloZid** [comment]
Some hints for you to be able to play around: To modify enemy/tower types refer to `enemy_settings.json` and `tower_settings.json`. To modify waves look at `waves.json`. To change the overall difficulty change the appropriate values in `game_settings.json`.

Basically there are 15 wave descriptions which are repeated. This means wave 16 is similar to wave 1. The total health of a wave is calculated in function of the total amount of credits you have already earned. It is an exponential function: `waveHealth = difficultyLinear * creditsEarned + difficultyModifier * creditsEarned ^ difficultyExponent`. The implementation of this equation is located in `WaveManager.java` method `updateWaveModifiers()`.

Have fun!

**Comment by reloZid** [comment]
Moving to #142.

**Comment by kiorato** [comment]
There isn't any problem to win against this lvl. My best score on the original map is lvl 134 / 7 670 215 pts.
You should upgrade your équipement instead of buy a new one.
