### ISSUE TITLE
lagging when the screen is full of "monsters" 

### ISSUE THREAD

**Issue by Bahjesaispas** [reloZid/android-anuto#14]
http://hpics.li/ad4eff6

As you can see on the picture the screen is full of "monsters". But on the screenshot you cannot see that at this point the game is lagging a lot !!

**Comment by Almtesh** [comment]
Yes, that's quite normal. Your phone is very busy to render all the assets on the screen. A lot of tower defense have this problem.

**Comment by mvdan** [comment]
You could look into profiling the app to see if the framerate drop could be avoided until a bigger number of enemies are on screen. Then you could open either issues or pull requests about specific issues that you find. But this one is just too broad as @Almtesh pointed out.

**Comment by reloZid** [comment]
I think there are two ways to address this problem:
* Optimizing the game engine (any hints are much appreciated! Like @mvdan pointed out, profiling would probably be the way to go)
* Altering the gameplay like limiting the total amount of active waves (maybe reduces the fun factor but would basically limit the total amount of enemies in game)

**Comment by mvdan** [comment]
Note that another strategy would be skipping frames. As in, make the game drop FPS instead of lag to render always the same number of frames per in-game second.

I don't know what the current FPS is, but perhaps you could make the app accept a range like 15-60. At best, it would do 60 frames per second, and at worst 15. You don't want it to drop to something like 4 frames per second.

**Comment by Almtesh** [comment]
Otherwise, you have large delays in waves

**Comment by Bahjesaispas** [comment]
You're losing the bonus if you do that. Maybe a button to do faster wave will be great too. Around wave 6X it's reeeeeaaaaaaally long.

**Comment by Xodem** [comment]
You should consider to use lengthsquared whenever possible. Sqrt is quite expensive. Maybe save the actual towerrange once (for displaying purposes in the popup) but calculate the squaredrange once and compare to that.

**Comment by Almtesh** [comment]
I heard about it too. It's a trick to save lot of time. I don't even know how to compute a square root.

**Comment by notpokey** [comment]
I think a lot of computing power must be used in tallying all of the damage done by all of the projectiles (tens of shots per second by each Gatling tower) to all of the hit counters (one for each enemy). I have a pretty robust phone, and it gets HOT playing this game. Is it really harder for the processor to render the graphics than it is to keep score?

I agree that most Tower Defense games that I've played slow down at some point, even on a computer. The only way to stop it from happening for sure seems to be to make the enemies stronger so the game ends earlier.

**Comment by civyshk** [comment]
I've replaced some distances with squared distances and it doesn't seem to make a big difference. What I see while profiling with lots of enemies, is that there are tons of calls to iterator methods like LazyIterator.hasNext, SmartIterator.fetchNext and similar.

I'm having problems running Android Device Monitor to further analyze the trace so I leave two useful trace files in this [zip here](https://drive.google.com/file/d/0B7aqNkw8z7q4RmpITXpoN2ZTU3M/view?usp=sharing).

**Comment by civyshk** [comment]
I've run the current version of the app in the emulator with +1000 enemies and it doesn't seem to lag. Is anybody still having lags?

2000 enemies now and still smooth. At 8x, however, it starts to drop frames, but who cares.

**Comment by reloZid** [comment]
Moving to #141.
