### ISSUE TITLE
google does evil

### ISSUE THREAD

**Issue by MalevolentGrin** [reloZid/android-anuto#145]
Is there a non-[google way](https://play.google.com/apps/testing/ch.logixisland.anuto) to signup for beta test?  I have removed all the google evil doing apps/services from my root'd phone.

Privacy is a Human Right.  Google is a Humans Rights violator on an epic scale.

**Comment by reloZid** [comment]
I don't know how to create beta releases for F-Droid. As a consequence you are automatically a beta tester if you are using F-Droid to install/update the game.
