### ISSUE TITLE
No damage from 500-point turret

### ISSUE THREAD

**Issue by tonyzhang617** [reloZid/android-anuto#15]
The 500-point turret does no damage to the enemies.

**Comment by SnarkBoojum** [comment]
The 500 credit turret slows them down, so it's normal that it doesn't do any damage!

**Comment by Almtesh** [comment]
Yes, we all know that a explanation of the game misses, that already ask in the issue #12.

**Comment by reloZid** [comment]
Like @SnarkBoojum pointed out, this turret is indeed supposed to do no damage. There is an issue for adding description to each unit: #16
