### ISSUE TITLE
Bullet Hose misses fast Fliers

### ISSUE THREAD

**Issue by blackboxlogic** [reloZid/android-anuto#151]
Bullet hoses sometimes miss fliers that are far away and traveling perpendicular. See bottom of image for clarity:
![image](https://user-images.githubusercontent.com/31355456/50663841-00c6d180-0f79-11e9-9197-4d1070f2f38d.png)

I suggest changing the bullet speed, or teaching bullet hoses to aim slightly ahead of their target.

Or, is this "part of the game"?

**Comment by reloZid** [comment]
These towers are programmed to aim ahead based on the targets current speed. They might miss if the speed of the target is changing. But this looks more like a bug.

**Comment by blackboxlogic** [comment]
I don't see any 'aim ahead' code:

[Shot.tick()](https://github.com/reloZid/android-anuto/blob/9c68ed93f72cd74b15a3705042d611354f59a3df/app/src/main/java/ch/logixisland/anuto/entity/shot/Shot.java#L26) seems to have bullets traveling in a straight line.

[MachineGun.tick()](https://github.com/reloZid/android-anuto/blob/master/app/src/main/java/ch/logixisland/anuto/entity/tower/MachineGun.java#L133) seems to use the direction to the target's _current_ location at fire-time.

Am I missing something? I might try to change MachineGun.tick() if I can get my computer set up for java dev.

**Comment by reloZid** [comment]
Sorry I was mistaken. It is the mortar which shoots ahead. But it probably makes sense to provide a similar mechanism here. Although it will be a bit more complicated to calculate, because the bullet travel time is not constant.

**Comment by reloZid** [comment]
Corrected in v0.5 (currently beta). The guns now aim such that the bullet will hit if the target keeps its current speed and direction.
