### ISSUE TITLE
Feature Request: Next Wave Preview

### ISSUE THREAD

**Issue by blackboxlogic** [reloZid/android-anuto#152]
Like Tetris™ shows the next piece, Anuto™ could help the player plan by showing either:
- a summary of the next wave, or
- a list of all waves (indicating completed waves)

Mostly, it would be helpful to know which types compose the next wave. For example:
![image](https://user-images.githubusercontent.com/31355456/50664413-fd344a00-0f7a-11e9-9ca6-c2c232b1ac5b.png)
in this image, Player knows that the next wave will include _soldiers_ and _runners_, and may strategize accordingly.

**Comment by reloZid** [comment]
I see that this would be a useful feature. But I'm not yet sure about how to visualize that with a proper look and feel. For me your suggestion makes the button looking a bit crammed. Maybe some sort of drop down menu which then also displays other stuff mentioned in issue #128.

**Comment by blackboxlogic** [comment]
Is there a way to merge
