### ISSUE TITLE
Undo for "next wave" button

### ISSUE THREAD

**Issue by spanezz** [reloZid/android-anuto#169]
A simple alternative to load/save, could be an undo for the last "next wave" button press.

This could be implemented by snapshotting the game status when "next wave" is pressed, and restoring it on undo.

It could be used to undo accidental presses, as well as wrong buy/sell actions since the last time "next wave" was pressed.

**Comment by reloZid** [comment]
A save/load feature has been added in v0.6. The problem with saving on each "next wave" press is that it takes around 200ms to save the game during which the game would be stuck.
