### ISSUE TITLE
Cannon shoots from its last position

### ISSUE THREAD

**Issue by mvdan** [reloZid/android-anuto#17]
If the cannon (third turret at second level) aims at a different angle when shooting, the projectile animation starts from its old position instead of the new one. Easily spotted if the cannon was shooting downward and suddenly shoots upward - the projectile appears to shoot from its back.

Same might happen with other turrets, haven't been able to tell very well.

**Comment by Almtesh** [comment]
You mean that the turret does not anticipate the target's position when the shot arrives on the target?
You're right, that strange since the two previous evolution of that turret shot bullets that follow the target.

**Comment by mvdan** [comment]
I'm not sure what you mean. The glitch can be seen at the moment that the bullet is shot, not when it lands.

**Comment by Almtesh** [comment]
Oh, sorry, totally not that at all.

**Comment by reloZid** [comment]
I can confirm that. The problem is that the show spawns before the turret has turned.
