### ISSUE TITLE
New strategies: how close they are to the end

### ISSUE THREAD

**Issue by mvdan** [reloZid/android-anuto#18]
This is similar to First/Last. Those keep track of the first/last in the order in which they were spawned. I would find First/Last in the order in which they are getting to the end more useful.

For example, if I have a sniper turret to catch those that run past my other turrets, I want the First as in the one that's closest to the end. But it will probably not be the first to spawn, as a faster enemy could be the first in progress but not the first to have spawned.

Don't know if these strategies should be added in parallel (with new names) or if they should replace the existing. I don't think I'd ever find the current ones useful.

**Comment by Almtesh** [comment]
That exists, it's the lock target option. Set it to false and it will select the good target at every shot.
Yes, the lock option is about targeting, not shooting.

**Comment by mvdan** [comment]
I understand lock is about targeting. What does locking mean, then? It locks to a target while it is in range, or while it is alive?

**Comment by Almtesh** [comment]
If you lock target, the weapon will shoot on the same target until it's dead or out of range.
If you don't lock target, the weapon will change the target if the target's status based on strategy changes.
For example, if you choose the First strategy, if a target if faster than the other, the nearby weapon will target the new first target only if the lock is to false.

@mvdan put the lock option to false, you will understand.

**Comment by mvdan** [comment]
That's what I intuitively understood as locking.

I opened this issue because I thought `First` targeted the first enemies to appear on the map, not those that were first in the race to the end. I think I was wrong, in which case this issue should be closed.

**Comment by mvdan** [comment]
Playing the game more and more, I realize I was wrong. Closing.
