### ISSUE TITLE
[Permission] Add comments to strings.xml files

### ISSUE THREAD

**Issue by berkaygunduzz** [reloZid/android-anuto#182]
I want to add short description comments to strings.xml files for all languages. They will be like [strings.xml](https://github.com/reloZid/android-anuto/files/5182483/strings.xml.txt) I will start it on my fork after your permission.

**Comment by reloZid** [comment]
Sure. Just keep in mind that other people might edit the translations using a graphical tool and the comments could get messed up after a while. This is why I only kept the main `strings.xml` file in a good shape so far.

**Comment by berkaygunduzz** [comment]
So will you merge after that adds (even in main strings.xml)?
