### ISSUE TITLE
[Permission] [Knowledge] Add new maps

### ISSUE THREAD

**Issue by berkaygunduzz** [reloZid/android-anuto#183]
I want to know that if i made my map.json file, can i add it? Are these the steps? : 
- Make map.json according to format of other maps
- Add map.json to app/src/main/res/raw
- Add `<string name="map_name">Name<string>` to strings.xml files
- Add `mMapInfos.add(new MapInfo("map_name", R.string.map_name, R.raw.map));` to MapRepository.java file

**Comment by reloZid** [comment]
As far as I remember these are all relevant steps, yes. If you like you can always open pull requests with new maps. Leave a comment if you have any issues.

**Comment by berkaygunduzz** [comment]
Thanks, i'm also making a map maker for that now. Not the best but if you want, i can share the source code's url after finishing it

**Comment by berkaygunduzz** [comment]
@reloZid [Here](https://github.com/berkaygunduzz/atdmc) is map making app.

**Comment by berkaygunduzz** [comment]
@reloZid Can i open a new issue named Adding New Maps? I will redirect to my project link, so when a person wants to add a new map, he can find the way easily.
