### ISSUE TITLE
Increasing Scroe after Game Over!

### ISSUE THREAD

**Issue by S-Gross** [reloZid/android-anuto#185]
Hi,

i observed that the score is still increasing after i am "Game Over!".
Instead of directly starting a new game, i just switched to another app.  
After some time i entered the game again, still with the game over screen but with a higher score. 
I could repeat this a few times until i increased my score by nearly 1million until all mobs run through the maze. 

Cheers
Stephan

**Comment by reloZid** [comment]
I could reproduce this when closing the app, not just switching. But this indeed not intended. Thanks for reporting.

**Comment by reloZid** [comment]
Fixed in v0.7.
