### ISSUE TITLE
Sound Effects

### ISSUE THREAD

**Issue by reloZid** [reloZid/android-anuto#2]

**Comment by Almtesh** [comment]
I suggest you to make sounds of lasers, machine gun and explosion with your mouth. It would be funny to have drawn assets with mouth-made sound.

**Comment by tmelikoff** [comment]
@Almtesh A couple of minutes ago I thought the same thing and came here to comment. Couldn't agree more.

**Comment by betsythefc** [comment]
I'd be willing to record myself making the noises!

**Comment by wesen1** [comment]
I don't like that idea. I prefer "real" sound effects.

**Comment by reloZid** [comment]
I think mouth-made sound effects would be really funny :) I guess the challenge would be that the game doesn't get annoying if you want to play it seriously, so of course there had to be an option to turn the effects off.

@betsythefc nice to hear that you would like to contribute :) If you want you can send me some samples and I will try to integrate them in a test version. Currently I'm quite busy, but I hope that I can start working on v0.2 in the next few weeks.

**Comment by betsythefc** [comment]
@reloZid Sure, I'll do a pull request with a sample or two!

**Comment by betsythefc** [comment]
I haven't forgotten, I have been trying to get access to the sound room at my work. I should be able to record soon!

**Comment by betsythefc** [comment]
I have recorded and submitted a pull request!

**Comment by reloZid** [comment]
Hi! Thanks a lot for your work, I'll try to integrate them ASAP.

**Comment by reloZid** [comment]
Finally integrated into master branch. Sorry that it took so long. I'll create an open beta version soon and publish the link. Or you can build and try the repo version yourself.
