### ISSUE TITLE
Teleporter sell value higher as its cost

### ISSUE THREAD

**Issue by Spunge** [reloZid/android-anuto#20]
You can buy and upgrade the 4th cannon for 3k and then sell it for ~4k.

This provides unlimites money.

**Comment by Almtesh** [comment]
So, #7 is not solved?

**Comment by Almtesh** [comment]
@Spunge what version do you use?

**Comment by Spunge** [comment]
Ah nevermind, was using 1.4. Upgraded to 1.5 and the issue seems solved. Sorry!
