### ISSUE TITLE
Incentive to advance waves doesn't scale fast enough

### ISSUE THREAD

**Issue by mvdan** [reloZid/android-anuto#21]
At level 49, I make almost 0.5k per dead enemy. The bonus for advancing the wave is around `480 (+800)`. I would never advance a wave then, as the extra money I would win is ridiculous - less than two enemies. In earlier levels, it's a much higher relative value.

**Comment by Almtesh** [comment]
That's strange, since the ennemies' lifeforce is well scaled.

**Comment by mvdan** [comment]
I can confim this trend stayed until I died at level 56. At most I saw something like `(+1000)`, which was still at most two enemies' worth.

**Comment by reloZid** [comment]
I addressed this issue in v0.3.
