### ISSUE TITLE
Fast Forward

### ISSUE THREAD

**Issue by wesen1** [reloZid/android-anuto#24]
I would like to have a fast forward button in this game. It would be useful to speed up the game especially for the rounds at the beginning when you have not many towers.

**Comment by beothorn** [comment]
Created a PR
https://github.com/reloZid/android-anuto/pull/97

**Comment by gomesar** [comment]
@reloZid. I think this was solved too ;]

**Comment by reloZid** [comment]
Sorry, forgot this one :) PR #97 is merged.
