### ISSUE TITLE
Colored theme

### ISSUE THREAD

**Issue by wesen1** [reloZid/android-anuto#25]
At the moment, only a few things are colored (laser, explosion, lifebars, range and not enough money to buy tower). I feel after a short time that the game becomes dull because of missing colors. I would like to have the option to have colored towers, missiles, enemies, walls and paths.

**Comment by jkufner** [comment]
I really like the pencil style. Don't make it too colorful.

**Comment by wesen1** [comment]
That's why I said :

> I  would like to have the **option** to have colored towers, missiles, enemies, walls and paths.

I knew that there must be people who like the current design.

**Comment by lightonflux** [comment]
I would like to see the upgrade level by colour. You can preserve the pencil style by doing sloppy hatching. See Crayon Physics Deluxe.

**Comment by gloryroad1** [comment]
How about coding the tower icons to show enhancement level. . .a simple, clear visual flag, such as adding a little circle or dot in the upper left corner for level 1, upper right for level 2, etc... Are there more than 4 enhancements for any tower?

**Comment by lightonflux** [comment]
> How about coding the tower icons to show enhancement level. . .a simple, clear visual flag, such as adding a little circle or dot in the upper left corner for level 1, upper right for level 2, etc...

Depending on the screen size it might be too hard to recognise. 

> Are there more than 4 enhancements for any tower? 
Yes some towers have 4 others have 9.

**Comment by gloryroad1** [comment]
Up to 4 enhancements would be easy to flag clearly with simple visual cues but 9 likely would be tough without a very clever code, even on my 8" screen.   Rather than a flag I guess a number would be required for that many.  Still, some indication of a tower's enhancement level would be helpful in quickly deciding what and where to reinforce during a fight.

**Comment by KatiaCooksCakes** [comment]
I think a nice way to colour code turrets and indicate their enhancement level would be to have them start off as white and fade the colour in the higher the level of the turret is. So a lvl 1 turret would be white, lvl 2 would only be very slightly coloured, level 3 slightly more and so on until lvl 9 which would be a very saturated colour. Of course that would make it pretty hard to see if a tower is level 4 or 5 (for example)

**Comment by zmk4** [comment]
How about a colorizing template so non-purists can tinker with non-strategy concerns?
