### ISSUE TITLE
Screen goes dark after screen timeout

### ISSUE THREAD

**Issue by StefanBrand** [reloZid/android-anuto#26]
What happens is that the screen times out during the game, when it should actually stay active.

I'm on a Fairphone FP1 / MT6589 chipset running KitKat 4.4.4.

Workaround is to set the screen time out higher.

**Comment by reloZid** [comment]
I assume this happens if you watch the game and don't touch the screen?

**Comment by mvdan** [comment]
@reloZid yeah. There are ways to tell Android to not let the screen dim and keep it awake, often used in games.

**Comment by newluck77** [comment]
> I assume this happens if you watch the game and don't touch the screen?

@reloZid Exactly, it happens when I'm waiting for the wave to pass, for example.
