### ISSUE TITLE
[Feature Request] Dynamic and more complex weapons

### ISSUE THREAD

**Issue by HassanHeydariNasab** [reloZid/android-anuto#28]
enhance, upgrade and "make it dynamic"!
Moving the weapons needs strategy and makes variety.
The lasers could upgrade to a new level that works together! It may makes zig-zag shapes or other synergy...

**Comment by reloZid** [comment]
Currently each tower has a damage bonus and a damage penalty against one enemy type. I thought about making the waves dynamic, so that an AI decides which enemy types are the most challenging ones based on your current tower setup. This would force you to build a variety of tower types.

**Comment by reloZid** [comment]
Closed due to inactivity.
