### ISSUE TITLE
[Feature request] Back button should not exit game.

### ISSUE THREAD

**Issue by muleyryan** [reloZid/android-anuto#30]
I just downloaded auto and have quit three games already by hitting the back button, expecting it to exit the tower detail menu.

**Comment by reloZid** [comment]
Fixed in master.

**Comment by ranit8** [comment]
Why can't the back button do the same thing as the home button, keeping game state as it exits? Now it is not doing anything at all, I can't think of that as a feature.

**Comment by reloZid** [comment]
Because you currently have no guarantee that the game state is kept. Devices with low memory will likely close the application instead of minimizing it. See #6.
