### ISSUE TITLE
Pause button

### ISSUE THREAD

**Issue by Tonat** [reloZid/android-anuto#41]
A pause button would be really appreciated as it would give the user time to build, enhance, upgrade, change strategy, ... during (!) a wave. Particularly with the longer waves it would help :)

**Comment by goldencut** [comment]
That would change the nature of the game, make it much easier, although sometimes I would like it too, when I'm losing..

**Comment by cptMikky** [comment]
It would make the game **a bit** easier. Or, perhaps, *less frustrating* in a few very specific situations, mostly involving external disturbances.

**Comment by reloZid** [comment]
With the latest commits I added a new menu. If you open the menu, the game is paused, but you can't make any changes (build, enhance, etc.). I think that should be enough, it would be less challenging if you can pause the game as soon as you see one enemy escaping and then build and upgrade a tower while the game is paused. It shall be a required skill to decide whether the tower setup is able to deal with the current wave.

**Comment by Tonat** [comment]
Fair enough, thanks reloZid!
