### ISSUE TITLE
No enemies appearing bug

### ISSUE THREAD

**Issue by edent** [reloZid/android-anuto#46]
Not sure how I made this happen. Restarted the game, accidently double tapped the 250 tower. Tower was purchased but not placed anywhere. Seemed to block enemies from appearing. I was able to press the next wave button to collect the bonus, but that was it. 

Haven't been able to replicate the issue since. 

Using the f-droid.org version. 
![screenshot_20161002-084000](https://cloud.githubusercontent.com/assets/837136/19019327/2d2dd510-887c-11e6-9dd8-dcc8e40c2351.png)

**Comment by SamSkulls** [comment]
Just had this happen, also using the f-droid version. I didn't touch any of the guns; I just hit the restart button after having a game over.

**Comment by reloZid** [comment]
For me this bug sounds like a threading issue which caused the game thread to die. For the 0.2 version a lot of the business logic changed to better separate the UI and game thread. In addition the whole application crashes will crash if the game thread has an exception (this allows sending a bug report which contains the stack trace). Please open a new issue if this should happen again.
