### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [reloZid/android-anuto#48]
It would be handy to have this app distributed through F-Droid. Do you think that would be feasible?

**Comment by Tonat** [comment]
From reading https://github.com/reloZid/android-anuto/blob/master/README.md
you can find https://f-droid.org/repository/browse/?fdid=ch.logixisland.anuto :)

**Comment by pizzamaker** [comment]
Oh neat! I must have missed this. Thanks :)
