### ISSUE TITLE
[Feature Request] Darker theme

### ISSUE THREAD

**Issue by quaap** [reloZid/android-anuto#49]
I love this game. I've noticed that the battery drain is very high, I think part of it is the bright background. It's also hard on my eyes to play it in the dark.

My original thought was to color invert all the pngs (either the files themselves or in memory after loading), but I whipped up a quick test by merely color-inverting plateau1.png and it looks good enough to me.

![screen capture](https://cloud.githubusercontent.com/assets/20132877/19484223/83aa5c36-951c-11e6-9b20-474534640922.png)

In BasicPlateau.java I changed:
s.sprite = Sprite.fromResources(R.drawable.plateau1, 4);
to
s.sprite = Sprite.fromResources(R.drawable.plateau2, 4);

Obviously it'd need a setting switch somewhere, or a toggle maybe?

Thanks!

![plateau2](https://cloud.githubusercontent.com/assets/20132877/19483919/728932e8-951b-11e6-90f3-47c60c6961fb.png)

**Comment by quaap** [comment]
I went ahead and did a quick and dirty conversion by inverting the pngs after loading and adjusting the foreground and background colors, just to see what it's look like:
![darktheme](https://cloud.githubusercontent.com/assets/20132877/19497400/ba8cca9c-9551-11e6-9113-22aa0777c59d.png)

The in-memory inverting adds big lags on loading and before waves with new Enemies, so if a dark theme were to be added the dark images would need to be static (unless there's a better way to invert them than what I'm doing), but I do like the look!

**Comment by quaap** [comment]
I was interested in learning more about Android programming, so I forked this and implemented the dark theme.  You can find it in the [darktheme branch](https://github.com/quaap/android-anuto/tree/darktheme).  You can see some screenshots [here](http://quaap.com/D/759ue9dzn).  I'm really new to Android, and Github for that matter, so I hope none of this is too out of line.

Feel free to use it, or not, as you see fit! :)

**Comment by reloZid** [comment]
Hi @quaap

Thanks a lot for your work! I just started arranging some stuff to finally begin working on some features for v0.2. I will surely have a look at how you implemented the color inversion. If you want you can also start a pull request to have your commits in this repository.

Cheers

**Comment by quaap** [comment]
Thanks!

**Comment by ralienpp** [comment]
I checked the screenshots and I think that a minor improvement would be to make the green less bright- it attracts too much attention because of very high contrast. I think that adjusting the green a bit (like the `comment` button below the reply form on Github) will make it easier on the eye.

**Comment by reloZid** [comment]
Integrated into master. Further discussions go into #8.
