### ISSUE TITLE
Highscore List

### ISSUE THREAD

**Issue by reloZid** [reloZid/android-anuto#5]

**Comment by goldencut** [comment]
yup, highscores would be lovely, gives the game a goal

**Comment by reloZid** [comment]
Actually I would like to have an online highscore list. Any ideas about how to prevent cheating? The only way I can think of is that a client has to send the entire replay which then gets validated by the server. But this is quite expensive to implement.

**Comment by stephennn** [comment]
I will look into implementing a local high score list this weekend. I wont attempt anything online as you are right, preventing cheating is a whole different set of problems. At least it makes a nice goal to try and do better than your past attempts.

**Comment by goldencut** [comment]
Can't wait to see the high score list. I'd actually prefer local high score list (at least at this stage) as the online ones tend to introduce bloat and delays to most apps. And not everyone have internet at hand all the time. Maybe add at later stage to the local high score list a button 'Upload best score to server'?

**Comment by jkufner** [comment]
Drop cheating protection. Simple list without protection is fine as long as there is no motivation to cheat (prices, benefits or so).

Replay would be nice to show how the score was achieved. The automatic verification on the server is not neccessary, at least not now.

A basic protection can be done using a hash with hidden sallt. The salt would be compiled into the application, so it would be hard to find for ordinary users and script kiddies.

**Comment by zmk4** [comment]
Sign score submissions

Accept scores from current build

key rotation

**Comment by reloZid** [comment]
Local highscores for each level implemented. Solve online highscore lists in a separate issue.
