### ISSUE TITLE
Help in the game itself

### ISSUE THREAD

**Issue by ralienpp** [reloZid/android-anuto#54]
I think that at the very first start the game should display a bullet-point list of rules (just like here, in the repository's readme).

I played it for a while and I was VERY frustrated at level 11 so I came here to open a bug report and say that there is **no way** that level is beatable. Before doing that, I started reading other issues and learned about teleports, level 56, upgrades... Obviously I was missing something (-:

Because there are no hints or instructions in the game itself, the discoverability of important features is minimal. I installed it directly from F-Droid, so I had no exposure to any documentation at all. I am surprised I got as far as level 11 just by placing ordinary equipment (-:

**Comment by jkufner** [comment]
I completely agree with this. The Help doesn't have to be big. Just a short description of gameplay and two sentences for each turret and each upgrade (with a picture of the turret).

**Comment by reloZid** [comment]
See also #16

**Comment by reloZid** [comment]
Done: v0.4 has a getting started tutorial.
