### ISSUE TITLE
[Bug] App crashes after selecting level for the second time

### ISSUE THREAD

**Issue by mrtwnklr** [reloZid/android-anuto#61]
Steps to reproduce: start app, select level, place tower, open tower info, close tower info, start next round, press back, after **select level** app crashes.

This bug was introduced with #50. The app crashes with the following exception:

> FATAL EXCEPTION: main
>                   Process: ch.logixisland.anuto, PID: 10769
>                   java.lang.IllegalStateException: Fragment TowerInfoFragment{eb96976} not attached to Activity
>                       at android.app.Fragment.getResources(Fragment.java:805)
>                       at ch.logixisland.anuto.view.game.TowerInfoFragment.refresh(TowerInfoFragment.java:145)

**Comment by reloZid** [comment]
This one is fixed. Dark theme is currently not available with the new menu, but I'm working on it.
