### ISSUE TITLE
Negative Credits

### ISSUE THREAD

**Issue by Tonat** [reloZid/android-anuto#68]
Steps to reproduce
- start any game
- drag+drop any defence towers you like, credits < 0 are possible

Yay my most successful round ever! But takes the fun away :(
Not sure whether it actually goes down to -∞ or has some negative limit

Version 0.2-1 (F-Droid)
Android 6.0.1

Example:
![tmp_14897-screenshot_20170210-233748-315063243](https://cloud.githubusercontent.com/assets/16524907/22848136/15ba176a-efea-11e6-8623-c5199fb9a512.png)

**Comment by zwergwolf** [comment]
Hi, I just noticed there's already an issue open on this.
I'm running the same version 0.2-1 (F-Droid), Android 4.4.4 

You can place any towers you like all over the field. They're marked red, so it looks like it shouldn' t work, but it does.

Another small graphical issue - I don't know if I should have started a new topic on that - is that when you place a 100-point-tower directly below a 500-point-tower, the upper dark part of the 100p is not visible (overlayed by the graphics of the 500p). See picture example in e.g. 5th row of the map.

![example](/storage/sdcard0/Pictures/Screenshots/Screenshot_2017-02-11-09-29-13.png)

**Comment by reloZid** [comment]
Thanks for reporting, I'll fix this ASAP (no lather than tomorrow).
