### ISSUE TITLE
Game frozen at level 27

### ISSUE THREAD

**Issue by diegocrzt** [reloZid/android-anuto#77]
When I play the game and reach level 27 the game just stop working without any problem message, even from android OS, just frozen screen

**Comment by reloZid** [comment]
Someone reported a similar problem to me. In this case Android showed the "application not responding" dialog. Unfortunately I wasn't able to reproduce the problem yet with my hardware. I would be very thankful if someone with this problem could start the application with the debugger attached and give me a hint where this problem happens. Apparently this issue exists on certain device/configurations only.
