### ISSUE TITLE
some stars heal faster than others

### ISSUE THREAD

**Issue by cptMikky** [reloZid/android-anuto#79]
At wave 71 I was so far able to kill two stars in what seems to be an "endless" configuration. By closely watching stars (and hoping they finally die) I noticed that some stars heal faster than other. i.e. some stars are able to restore full health while under constant beating while others lose their health eventually. These are always instances of lone stars at the same choke point receiving full beating possible.

**Comment by reloZid** [comment]
Since v3.0 healer effects do not stack anymore.
