### ISSUE TITLE
Dark/Inverted mode needed

### ISSUE THREAD

**Issue by osalas88** [reloZid/android-anuto#8]
After playing the game for 10~15 mins, I got it burned into my LCD screen. I have an LG G4, it is a known problem. I assume that a dark mode would avoid such problem.

Overall great game,
Cheers

**Comment by reloZid** [comment]
Never would have thought about that :) I think the implementation wouldn't be that hard, the question is where to place this setting. Depends on #12.

**Comment by osalas88** [comment]
Alienblue for iOS changes from night mode to day mode when tapping 3 times in the "titlebar",  maybe tapping 3 times in the empty space between the guns and the buttons could do the trick.

**Comment by schachmat** [comment]
That would not be intuitive.

**Comment by reloZid** [comment]
Theme is now changeable through the menu.
