### ISSUE TITLE
Russian and Ukrainian translations

### ISSUE THREAD

**Issue by s-chizhik** [reloZid/android-anuto#80]
Hi! I'd like to translate game texts to Russian and Ukrainian language. May I send you PR or such changes is not essential?

**Comment by reloZid** [comment]
Of course you can send me a PR! I think there is already an Ukrainian translation on the master branch but it hasn't been released yet.

**Comment by s-chizhik** [comment]
Now I see.
Here PR with Russian lang and a bit fixed Ukrainian: https://github.com/reloZid/android-anuto/pull/81

**Comment by reloZid** [comment]
Merged and integrated in release 0.2-3
