### ISSUE TITLE
stars too powerful beyond wave 70

### ISSUE THREAD

**Issue by cptMikky** [reloZid/android-anuto#83]
There are several "wave unbeatable" and "game too hard" issues, lots of replies and tips in them but in the end none of these issues directly address the actual problem - stars are just too powerful in higher levels.

A few suggestions on stars balancing have been posted and I'd like to sum them here.
My suggestions would be (in order of my personal preference):

- a turret that reduces or disables star's healing power temporarily - maybe third upgrade to slow turret?
- do not stack heal effect
- stars can't heal other stars (except self)
- reduce stacking effect for each additional healer in the area
- one heal should heal a fixed number of HP and distribute it among all units in the effect's area (maybe combined with reduced stacking)
 
Other suggestions (in no particular order):

- stars can heal other units but cannot self-heal
- very reduced maximum life
- stars can heal other stars but with less effectiveness
- stars only heal themselves

**Comment by b100w11** [comment]
I agree about the stars being too powerfull. Wave 76 was running for about 10h, after that the waves were cleaned in 10-30min per wave. After 4h at level 85 with no kills I abandoned the game.
I support the idea of the fixed HP regeneration distributed among the units.

**Comment by doctormo** [comment]
I adjusted my own copy of the game to try and rebalance it. There's very little you can do actually since the monsters become more powerful in an exponential way, but the turrets improve until they reach a cap and then you're toast.

The game needs some sort of end game that isn't waiting 80h and burning two tons of coal to run the game level.

**Comment by reloZid** [comment]
Nerfing the stars (don't let heal effect stack seems the most appropriate option to me) would let you go some levels further. But this actually does not solve the problem of very long running waves. This is why initially teleport turrets could not teleport the same enemy twice (see #45), but this approach apparently was not very intuitive. I agree that the stars should be nerfed in some way, but the teleport towers needs a nerf too. Any ideas?

**Comment by cptMikky** [comment]
Some kind of "teleport resistance buildup" perhaps? Every time a unit is teleported (by any teleport) it's "resistance" increases which will result in shorter setback. Also the attack range of teleport towers can be lowered and/or price increased.

**Comment by reloZid** [comment]
Closing this. The solution in the current release is the following:
* Heal effect of stars does not stack anymore
* Each enemy can be just teleported once (indicated by a purple bubble)
