### ISSUE TITLE
[Feature request] Enemy counter

### ISSUE THREAD

**Issue by b100w11** [reloZid/android-anuto#84]
As an improvement it would be nice to have a counter of the attacker units on the screen. In the higher levels when the attackers are stacked one on the other it's very difficult to have an idea of how many of them are still left.

It could be put on the right of the lives counter on the top.

**Comment by gomesar** [comment]
I saw that PR #97 creates another TextView, so I've tried to reuse 'wave info string', changing from `Wave: N` to `Wave: N (C)`. where C is the counter.
Pull Request #98

**Comment by reloZid** [comment]
#98 merged.
